services:
  postgres:
    image: postgres:latest
    container_name: crecer_db_1
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-saved_articles}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
  api:
    build: ./api
    depends_on:
      - postgres
    ports:
      - "8000:8000"

  app:
    build: ./crecer
    ports:
      - "3001:3000"
    depends_on:
      - api

volumes:
  postgres_data:
